name: bamAlignCleaner-CI

on: [push, pull_request]


jobs:
  sam2lca_ci:
    name: bamAlignCleaner-CI
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, '[skip_ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          environment-file: environment.yml
          activate-environment: bamAlignCleaner
      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Install bamAlignCleaner
        shell: bash -l {0}
        run: |
          pip install .
      - name: Check bamAlignCleaner help message
        shell: bash -l {0}
        run: |
          bamAlignCleaner --help
      - name: Check bamAlignCleaner on test data
        shell: bash -l {0}
        run: |
          bamAlignCleaner -o test.bam tests/data/test.bam
          bamAlignCleaner -m index_stat -o test.bam tests/data/test.bam
          bamAlignCleaner -r tests/data/reflist2.txt tests/data/test.bam
          bamAlignCleaner -f tests/data/ref.fa tests/data/test.bam